.class public Lcom/xiaomi/ai/api/MultiModal;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/xiaomi/ai/api/MultiModal$VoiceModalConfig;,
        Lcom/xiaomi/ai/api/MultiModal$VisionRecognizeStarted;,
        Lcom/xiaomi/ai/api/MultiModal$VisionRecognizeResult;,
        Lcom/xiaomi/ai/api/MultiModal$VisionRecognizeFinished;,
        Lcom/xiaomi/ai/api/MultiModal$VisionRecognizeAggregateResult;,
        Lcom/xiaomi/ai/api/MultiModal$VisionImage;,
        Lcom/xiaomi/ai/api/MultiModal$VideoConfig;,
        Lcom/xiaomi/ai/api/MultiModal$UploadMultiModalMessage;,
        Lcom/xiaomi/ai/api/MultiModal$UploadMultiModal;,
        Lcom/xiaomi/ai/api/MultiModal$UITips;,
        Lcom/xiaomi/ai/api/MultiModal$TranslationParam;,
        Lcom/xiaomi/ai/api/MultiModal$SwitchOperation;,
        Lcom/xiaomi/ai/api/MultiModal$Switch;,
        Lcom/xiaomi/ai/api/MultiModal$SingleChar;,
        Lcom/xiaomi/ai/api/MultiModal$ResourceInfo;,
        Lcom/xiaomi/ai/api/MultiModal$RequestRobotIdentify;,
        Lcom/xiaomi/ai/api/MultiModal$RequestCarIdentify;,
        Lcom/xiaomi/ai/api/MultiModal$RefItem;,
        Lcom/xiaomi/ai/api/MultiModal$PersonalDataUnderstand;,
        Lcom/xiaomi/ai/api/MultiModal$PersonalDataSearch;,
        Lcom/xiaomi/ai/api/MultiModal$PersonalDataContext;,
        Lcom/xiaomi/ai/api/MultiModal$PersonalData;,
        Lcom/xiaomi/ai/api/MultiModal$Paragraph;,
        Lcom/xiaomi/ai/api/MultiModal$OpenMultiModal;,
        Lcom/xiaomi/ai/api/MultiModal$OCREntity;,
        Lcom/xiaomi/ai/api/MultiModal$OCR;,
        Lcom/xiaomi/ai/api/MultiModal$MultiModalState;,
        Lcom/xiaomi/ai/api/MultiModal$MultiModalScenesMessage;,
        Lcom/xiaomi/ai/api/MultiModal$MultiModalParam;,
        Lcom/xiaomi/ai/api/MultiModal$MultiModalContext;,
        Lcom/xiaomi/ai/api/MultiModal$MultiModalContent;,
        Lcom/xiaomi/ai/api/MultiModal$MediaStreamStarted;,
        Lcom/xiaomi/ai/api/MultiModal$MediaStreamFinished;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIVehicleInfo;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIResourceItem;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIPhoneNumberInfo;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIPassportInfo;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIOtherCardInfo;,
        Lcom/xiaomi/ai/api/MultiModal$MIAILicenseInfo;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIInvoiceInfo;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIIDCardInfo;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIEmailInfo;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIBankCardInfo;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIAddressInfo;,
        Lcom/xiaomi/ai/api/MultiModal$MIAIAccountInfo;,
        Lcom/xiaomi/ai/api/MultiModal$Location;,
        Lcom/xiaomi/ai/api/MultiModal$LoadXiaoAiImage;,
        Lcom/xiaomi/ai/api/MultiModal$Line;,
        Lcom/xiaomi/ai/api/MultiModal$ImageUnderstand;,
        Lcom/xiaomi/ai/api/MultiModal$ImageStreamStarted;,
        Lcom/xiaomi/ai/api/MultiModal$ImageStreamFinished;,
        Lcom/xiaomi/ai/api/MultiModal$ImageResolution;,
        Lcom/xiaomi/ai/api/MultiModal$ImageLocation;,
        Lcom/xiaomi/ai/api/MultiModal$ImageInfo;,
        Lcom/xiaomi/ai/api/MultiModal$HumanDetectionParam;,
        Lcom/xiaomi/ai/api/MultiModal$GestureParam;,
        Lcom/xiaomi/ai/api/MultiModal$FormChooseResultEvent;,
        Lcom/xiaomi/ai/api/MultiModal$FileUploadResult;,
        Lcom/xiaomi/ai/api/MultiModal$FileUploadInfo;,
        Lcom/xiaomi/ai/api/MultiModal$FaceParam;,
        Lcom/xiaomi/ai/api/MultiModal$EyeContactRecognizeResult;,
        Lcom/xiaomi/ai/api/MultiModal$EyeContactInfo;,
        Lcom/xiaomi/ai/api/MultiModal$ExecutionResultDetail;,
        Lcom/xiaomi/ai/api/MultiModal$ExecutionResult;,
        Lcom/xiaomi/ai/api/MultiModal$DriverInfo;,
        Lcom/xiaomi/ai/api/MultiModal$DriverHoldPhoneInfo;,
        Lcom/xiaomi/ai/api/MultiModal$DriverGazeAreaInfo;,
        Lcom/xiaomi/ai/api/MultiModal$DocInfo;,
        Lcom/xiaomi/ai/api/MultiModal$CircleInfo;,
        Lcom/xiaomi/ai/api/MultiModal$CarSeatInfo;,
        Lcom/xiaomi/ai/api/MultiModal$CarIdentifyResult;,
        Lcom/xiaomi/ai/api/MultiModal$CarIdentifyItem;,
        Lcom/xiaomi/ai/api/MultiModal$CarIdentifyCoordinate;,
        Lcom/xiaomi/ai/api/MultiModal$AudioConfig;,
        Lcom/xiaomi/ai/api/MultiModal$AiSearch;,
        Lcom/xiaomi/ai/api/MultiModal$AiMemorySearch;,
        Lcom/xiaomi/ai/api/MultiModal$AiInsert;,
        Lcom/xiaomi/ai/api/MultiModal$VisionRecognizeType;,
        Lcom/xiaomi/ai/api/MultiModal$VisionImageSource;,
        Lcom/xiaomi/ai/api/MultiModal$UseAiMemoryScene;,
        Lcom/xiaomi/ai/api/MultiModal$UploadMultiModalScene;,
        Lcom/xiaomi/ai/api/MultiModal$UploadMultiModalMessageCode;,
        Lcom/xiaomi/ai/api/MultiModal$UIState;,
        Lcom/xiaomi/ai/api/MultiModal$RobotIdentifyCameraLocation;,
        Lcom/xiaomi/ai/api/MultiModal$ResourceType;,
        Lcom/xiaomi/ai/api/MultiModal$OCREntityType;,
        Lcom/xiaomi/ai/api/MultiModal$MultiModalScenesCode;,
        Lcom/xiaomi/ai/api/MultiModal$MultiModalContentTag;,
        Lcom/xiaomi/ai/api/MultiModal$MultiModalContentScene;,
        Lcom/xiaomi/ai/api/MultiModal$MultiModalContentImageTask;,
        Lcom/xiaomi/ai/api/MultiModal$MediaModalName;,
        Lcom/xiaomi/ai/api/MultiModal$MediaCodecType;,
        Lcom/xiaomi/ai/api/MultiModal$LoadImageScene;,
        Lcom/xiaomi/ai/api/MultiModal$ImageQuality;,
        Lcom/xiaomi/ai/api/MultiModal$ImageFormat;,
        Lcom/xiaomi/ai/api/MultiModal$ImageDecodeAlgo;,
        Lcom/xiaomi/ai/api/MultiModal$GestureType;,
        Lcom/xiaomi/ai/api/MultiModal$FileUploadStatus;,
        Lcom/xiaomi/ai/api/MultiModal$FeatureName;,
        Lcom/xiaomi/ai/api/MultiModal$DriverHoldPhonePosition;,
        Lcom/xiaomi/ai/api/MultiModal$DriverGazeArea;,
        Lcom/xiaomi/ai/api/MultiModal$DocType;,
        Lcom/xiaomi/ai/api/MultiModal$CarSeatStatus;,
        Lcom/xiaomi/ai/api/MultiModal$CarIdentifyLocation;,
        Lcom/xiaomi/ai/api/MultiModal$AiInsertScene;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
