.class public Lcom/xiaomi/ai/api/intent/actions;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/xiaomi/ai/api/intent/actions$ZoomOutMinAction;,
        Lcom/xiaomi/ai/api/intent/actions$ZoomOutAction;,
        Lcom/xiaomi/ai/api/intent/actions$ZoomInMaxAction;,
        Lcom/xiaomi/ai/api/intent/actions$ZoomInAction;,
        Lcom/xiaomi/ai/api/intent/actions$WatchAction;,
        Lcom/xiaomi/ai/api/intent/actions$UpgradeAction;,
        Lcom/xiaomi/ai/api/intent/actions$UnlockAction;,
        Lcom/xiaomi/ai/api/intent/actions$UninstallAction;,
        Lcom/xiaomi/ai/api/intent/actions$TurnUpAction;,
        Lcom/xiaomi/ai/api/intent/actions$TurnOnAction;,
        Lcom/xiaomi/ai/api/intent/actions$TurnOffAction;,
        Lcom/xiaomi/ai/api/intent/actions$TurnDownAction;,
        Lcom/xiaomi/ai/api/intent/actions$TransferAction;,
        Lcom/xiaomi/ai/api/intent/actions$TakeAction;,
        Lcom/xiaomi/ai/api/intent/actions$SwitchAction;,
        Lcom/xiaomi/ai/api/intent/actions$SubscribeAction;,
        Lcom/xiaomi/ai/api/intent/actions$StopReadAction;,
        Lcom/xiaomi/ai/api/intent/actions$StopAction;,
        Lcom/xiaomi/ai/api/intent/actions$StartAction;,
        Lcom/xiaomi/ai/api/intent/actions$SleepAction;,
        Lcom/xiaomi/ai/api/intent/actions$SingAction;,
        Lcom/xiaomi/ai/api/intent/actions$ShutdownAction;,
        Lcom/xiaomi/ai/api/intent/actions$SetUpAction;,
        Lcom/xiaomi/ai/api/intent/actions$SetAction;,
        Lcom/xiaomi/ai/api/intent/actions$SendAction;,
        Lcom/xiaomi/ai/api/intent/actions$SearchAction;,
        Lcom/xiaomi/ai/api/intent/actions$ScanAction;,
        Lcom/xiaomi/ai/api/intent/actions$RunAction;,
        Lcom/xiaomi/ai/api/intent/actions$RotateAction;,
        Lcom/xiaomi/ai/api/intent/actions$RestoreAction;,
        Lcom/xiaomi/ai/api/intent/actions$RequireAction;,
        Lcom/xiaomi/ai/api/intent/actions$RepostAction;,
        Lcom/xiaomi/ai/api/intent/actions$ReplyAction;,
        Lcom/xiaomi/ai/api/intent/actions$RegisterAction;,
        Lcom/xiaomi/ai/api/intent/actions$RefreshAction;,
        Lcom/xiaomi/ai/api/intent/actions$RecoverAction;,
        Lcom/xiaomi/ai/api/intent/actions$RecommendAction;,
        Lcom/xiaomi/ai/api/intent/actions$ReceiveAction;,
        Lcom/xiaomi/ai/api/intent/actions$RebootAction;,
        Lcom/xiaomi/ai/api/intent/actions$ReadAction;,
        Lcom/xiaomi/ai/api/intent/actions$ReInputAction;,
        Lcom/xiaomi/ai/api/intent/actions$ProjectAction;,
        Lcom/xiaomi/ai/api/intent/actions$PostAction;,
        Lcom/xiaomi/ai/api/intent/actions$PlayAction;,
        Lcom/xiaomi/ai/api/intent/actions$PinAction;,
        Lcom/xiaomi/ai/api/intent/actions$PayAction;,
        Lcom/xiaomi/ai/api/intent/actions$PauseAction;,
        Lcom/xiaomi/ai/api/intent/actions$OrderAction;,
        Lcom/xiaomi/ai/api/intent/actions$OptimizeAction;,
        Lcom/xiaomi/ai/api/intent/actions$OpenAction;,
        Lcom/xiaomi/ai/api/intent/actions$ModifyAction;,
        Lcom/xiaomi/ai/api/intent/actions$MeasureAction;,
        Lcom/xiaomi/ai/api/intent/actions$LoginAction;,
        Lcom/xiaomi/ai/api/intent/actions$LockAction;,
        Lcom/xiaomi/ai/api/intent/actions$ListenAction;,
        Lcom/xiaomi/ai/api/intent/actions$LikeAction;,
        Lcom/xiaomi/ai/api/intent/actions$LiftUpAction;,
        Lcom/xiaomi/ai/api/intent/actions$JumpAction;,
        Lcom/xiaomi/ai/api/intent/actions$InstallAction;,
        Lcom/xiaomi/ai/api/intent/actions$InformAction;,
        Lcom/xiaomi/ai/api/intent/actions$HangUpAction;,
        Lcom/xiaomi/ai/api/intent/actions$FullScreenAction;,
        Lcom/xiaomi/ai/api/intent/actions$ExitAction;,
        Lcom/xiaomi/ai/api/intent/actions$EditAction;,
        Lcom/xiaomi/ai/api/intent/actions$DownloadAction;,
        Lcom/xiaomi/ai/api/intent/actions$DowndipAction;,
        Lcom/xiaomi/ai/api/intent/actions$DislikeAction;,
        Lcom/xiaomi/ai/api/intent/actions$DisconnectAction;,
        Lcom/xiaomi/ai/api/intent/actions$DeleteAction;,
        Lcom/xiaomi/ai/api/intent/actions$DeactivateAction;,
        Lcom/xiaomi/ai/api/intent/actions$CreateAction;,
        Lcom/xiaomi/ai/api/intent/actions$ContinuePlayAction;,
        Lcom/xiaomi/ai/api/intent/actions$ContinueAction;,
        Lcom/xiaomi/ai/api/intent/actions$ConnectAction;,
        Lcom/xiaomi/ai/api/intent/actions$ConfirmAction;,
        Lcom/xiaomi/ai/api/intent/actions$CompareAction;,
        Lcom/xiaomi/ai/api/intent/actions$CollectAction;,
        Lcom/xiaomi/ai/api/intent/actions$CloseAction;,
        Lcom/xiaomi/ai/api/intent/actions$CleanAction;,
        Lcom/xiaomi/ai/api/intent/actions$CheckAction;,
        Lcom/xiaomi/ai/api/intent/actions$CancelSendingAction;,
        Lcom/xiaomi/ai/api/intent/actions$CancelOpenAction;,
        Lcom/xiaomi/ai/api/intent/actions$CancelDeleteAction;,
        Lcom/xiaomi/ai/api/intent/actions$CancelCreateAction;,
        Lcom/xiaomi/ai/api/intent/actions$CancelCollectAction;,
        Lcom/xiaomi/ai/api/intent/actions$CancelCloseAction;,
        Lcom/xiaomi/ai/api/intent/actions$CancelAction;,
        Lcom/xiaomi/ai/api/intent/actions$BootAction;,
        Lcom/xiaomi/ai/api/intent/actions$BlockAction;,
        Lcom/xiaomi/ai/api/intent/actions$AskAction;,
        Lcom/xiaomi/ai/api/intent/actions$ApplyAction;,
        Lcom/xiaomi/ai/api/intent/actions$AnswerAction;,
        Lcom/xiaomi/ai/api/intent/actions$AdjustUpAction;,
        Lcom/xiaomi/ai/api/intent/actions$AdjustRightAction;,
        Lcom/xiaomi/ai/api/intent/actions$AdjustOutwardAction;,
        Lcom/xiaomi/ai/api/intent/actions$AdjustMinAction;,
        Lcom/xiaomi/ai/api/intent/actions$AdjustMaxAction;,
        Lcom/xiaomi/ai/api/intent/actions$AdjustLeftAction;,
        Lcom/xiaomi/ai/api/intent/actions$AdjustInwardAction;,
        Lcom/xiaomi/ai/api/intent/actions$AdjustForwardAction;,
        Lcom/xiaomi/ai/api/intent/actions$AdjustDownAction;,
        Lcom/xiaomi/ai/api/intent/actions$AdjustBackwardAction;,
        Lcom/xiaomi/ai/api/intent/actions$AddAction;,
        Lcom/xiaomi/ai/api/intent/actions$ActivateAction;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
